### ISSUE TITLE
[SPIKE] Investigate using AWS Airflow

### ISSUE THREAD

**Issue by jermnelson** [LD4P/ils-middleware#13]
Investigate the use of [MWAA](https://aws.amazon.com/managed-workflows-for-apache-airflow/)(Amazon Managed Workflows for Apache Airflow) for Sinopia. Alternative is to host the individual components using [Fargate](https://aws.amazon.com/fargate/) and [RDS](https://aws.amazon.com/rds/).

**Comment by aaron-collier** [comment]
@jermnelson I'll find the links when I did this spike for DLME, one thing I learned is that MWAA is surprisingly expensive compared to deploying in ECS.

**Comment by jermnelson** [comment]
I agree; I think we should go the DLME route 😄 . Closing this issue. I'll add follow-up ticket(s)
