### ISSUE TITLE
rdf2marc Error Handling

### ISSUE THREAD

**Issue by jermnelson** [LD4P/ils-middleware#134]
When the `rdf2marc` returns an error, we are not raising an Error within the Task correctly. For example, when `https://api.stage.sinopia.io/resource/41c4ddba-4d38-44d0-b94b-4dfef0f6c338` is processed the following Error message is returned:

```json
{'error_message': 'RDF2MARC conversion failed for https://api.stage.sinopia.io/resource/41c4ddba-4d38-44d0-b94b-4dfef0f6c338, error: Work (bf:instanceOf) not specified for Instance'}
```
We should raise an exception to fail the Task instead of continuing with a **success** status because the subsequent task `download_marc` fails because the marc record is not available in the S3 bucket.

**Comment by jcoyne** [comment]
@jermnelson the Sinopia editor depends on this being a success status with an error message returned.

**Comment by jermnelson** [comment]
Closing in favor of https://github.com/LD4P/ils-middleware/issues/148
