### ISSUE TITLE
Provision production Airflow instance

### ISSUE THREAD

**Issue by jermnelson** [LD4P/ils-middleware#144]
Create a TF PR duplicating Staging/Development changes to support Airflow environment for Sinopia's production environment. We will need to coordinate with Ops because they will need to help troubleshoot/apply an TF changes. 

We also need to do the following:
- Make network firewall changes to all the new Airflow environment access to Stanford's Symphony production environment
- Create a Sinopia login for Production Symphony environment
- Create a specific sinopia_production shard_configs branch with configuration values uses to deploy

**Comment by jcoyne** [comment]
@jermnelson I don't understand the final two bullets in this list. Can you expand on this?

**Comment by jermnelson** [comment]
@jcoyne, I updated the second-to-last bullet point, basically we need `LibSys` to create a Sinopia user and password in our Symphony production environment that we can use to create/overly MARC records. Since login info will be different from the dev Symphony  credentials will be different than what we use on stage and development, I thought we could store it `shared_configs`, however the better place may be in TF.

**Comment by jermnelson** [comment]
Finished
