### ISSUE TITLE
Add new Inventory Record in FOLIO

### ISSUE THREAD

**Issue by jermnelson** [LD4P/ils-middleware#2]
Use Okapi Inventory API to create FOLIO Records (can be [Instance](https://wiki.folio.org/pages/viewpage.action?pageId=54888353)

This will likely need an Airflow [Connection](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html) for each FOLIO's environment Okapi endpoint that has `mod-inventory` enabled for use.

Currently have an open ticket in EBSCO https://github.com/FOLIO-FSE/MARC21-To-FOLIO/issues/77 to see if they will publish their module to pypi so we can leverage some of their existing Python classes without needing a local copy of their repo.

**Comment by jcoyne** [comment]
Is the intention here to wait until the EBSCO ticket is resolved before taking action?

**Comment by jermnelson** [comment]
I'm not sure we can wait until they act. We may be able to install this with `poetry add` via a git dependency https://python-poetry.org/docs/cli/#add but would need to be investigated.
