### ISSUE TITLE
Deploy Airflow via Kubernetes

### ISSUE THREAD

**Issue by jermnelson** [LD4P/ils-middleware#22]
Instead of Fargate

**Comment by aaron-collier** [comment]
Capturing my investigation notes here:

- Following https://towardsdatascience.com/setting-up-data-pipelines-using-apache-airflow-on-kubernetes-4506baea3ce0 and the linked helm chart it is very easy to get airflow up and running in kubernetes (locally).

**Comment by aaron-collier** [comment]
I was easily able to deploy to EKS via the helm chart. There are a few outstanding questions (which I will start to capture here) before closing this.

**Comment by aaron-collier** [comment]
@jermnelson / @jgreben - I think this needs to go back to either you guys or OPs to work through establishing everything necessary for the ingress.

**Comment by aaron-collier** [comment]
Or rather, this may be closable as we've already deployed - but the remainder is in #58.

**Comment by aaron-collier** [comment]
Complete: https://airflow.development.sinopia.io/login/?next=https%3A%2F%2Fairflow.development.sinopia.io%2Fhome
