### ISSUE TITLE
Create new AWS IAM Role for SQS

### ISSUE THREAD

**Issue by jermnelson** [LD4P/ils-middleware#37]
Currently in Sinopia's Development and Stage environments, we are using the `DevelopersRole` for both sending and receiving messages. We need to create a custom role for SQS that can be assigned to both of these queues.

**Comment by aaron-collier** [comment]
@jermnelson I'm wondering if we need a new role here or if we can use the existing ECS Execution role (as the sinopia_api container should be running under that role if I'm understanding correctly). I have currently put that role in the policy document (https://github.com/sul-dlss/terraform-aws/pull/892).

I wouldn't suggest closing this until we verify the structure is complete however.
