### ISSUE TITLE
Email Tasks for Success and Failures 

### ISSUE THREAD

**Issue by jermnelson** [LD4P/ils-middleware#39]
When a DAG completes or on errors, email the cataloger that the Sinopia resource was successfully imported into the ILS with either the CATKEY (Symphony) or the HRID (FOLIO). We should also email the cataloger if the DAG fails along with any context about the failed task(s).

We should use AWS [SES](https://airflow.apache.org/docs/apache-airflow/stable/howto/email-config.html?highlight=ses#send-email-using-aws-ses) as we are already doing for Sinopia email.

**Comment by jmartin-sul** [comment]
success case addressed by #64, filed #65 for dealing with task failure
