### ISSUE TITLE
Use Hashcorp Secrets Vault for AWS Creditials

### ISSUE THREAD

**Issue by jermnelson** [LD4P/ils-middleware#40]
For the AWS SQSSensor, we are setting the AWS credentials through the [UI](https://github.com/LD4P/ils-middleware/wiki/AWS-SQS#setting-up-aws-airflow-connection). We should instead use [Hashicorp Vault Secrets Backend](https://airflow.apache.org/docs/apache-airflow-providers-hashicorp/stable/secrets-backends/hashicorp-vault.html#hashicorp-vault-secrets) to retrieve these values.

**Comment by aaron-collier** [comment]
Capturing notes here as I work through the info.

Looks like we'll need HVAC: https://github.com/hvac/hvac
