### ISSUE TITLE
pull access denied for ld4p/ils-middleware...

### ISSUE THREAD

**Issue by jimfhahn** [LD4P/ils-middleware#43]
Hi all - I've been enjoying the recent talks on the ils middleware and wanted to also try out Alma in this stack, which is what we are using at Penn. Wondering if there are any permission friendly containers I can access? Currently getting this error when I try to run the compose:

pull access denied for ld4p/ils-middleware, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by jermnelson** [comment]
@jimfhahn we currently haven't pushed up an image for ils-middleware. If you clone this repository locally, you should be able to bring up Airflow with the existing DAGs with `docker compose up`.

**Comment by jimfhahn** [comment]
Thanks maybe, I have the wrong branch? I've followed the steps in the README and this is what I get:

(base) metadatajh:ils-middleware jimhahn$ docker compose up
[+] Running 0/7
 ⠿ airflow-worker Error                                                    1.2s
 ⠿ airflow-init Error                                                      1.2s
 ⠿ airflow-webserver Error                                                 1.2s
 ⠿ flower Error                                                            1.2s
 ⠿ redis Error                                                             1.2s
 ⠿ airflow-scheduler Error                                                 1.2s
 ⠿ postgres Error                                                          1.2s
Error response from daemon: pull access denied for ld4p/ils-middleware, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by jermnelson** [comment]
Pushed up image `ld4p/ils-middlware:latest` to Github. Closing.
