### ISSUE TITLE
Create K8 Ingress for Airflow

### ISSUE THREAD

**Issue by jermnelson** [LD4P/ils-middleware#58]
We need to create an Ingress (using a nginx image) pod so that we directly access Airflow web server in our Kubernetes environment.

**Comment by aaron-collier** [comment]
See: https://github.com/sul-dlss/terraform-aws/pull/903/files

**Comment by aaron-collier** [comment]
Complete: https://airflow.development.sinopia.io/login/?next=https%3A%2F%2Fairflow.development.sinopia.io%2Fhome
