### ISSUE TITLE
Test Stanford DAG trigger rules

### ISSUE THREAD

**Issue by jermnelson** [LD4P/ils-middleware#84]
As mentioned in @jmartin-sul PR 83 [comment](https://github.com/LD4P/ils-middleware/pull/83#issue-769503594), we want a test to confirm that the trigger relationship for `notify_on_task_failure` task is working correctly for any upstream task failures.

**Comment by jmartin-sul** [comment]
picking this up for now because i think i'll end up doing it as a natural part of #85
