### ISSUE TITLE
FOLIO Login Task

### ISSUE THREAD

**Issue by jermnelson** [LD4P/ils-middleware#92]
We need to log into FOLIO Okapi API [mod-login](https://s3.amazonaws.com/foliodocs/api/mod-login/login.html#authn_login_post) endpoint with a valid FOLIO user and password and save the resulting JWT in the header to XCOM for use by downstream tasks.

BLOCKS #93 
BLOCKS #94

Another approach would be to use the EBSCO FOLIO client for integrating with Okapi API https://github.com/FOLIO-FSE/FolioClient that could replace or wrap this task.

Assumes we have a user and password already created in FOLIO, the POST call using the `requests` module would look like:

```python
result = requests.post(
   'https://okapi-folio.stanford.edu/authn/login',
  headers={"X-Okapi-Tenant": "sul"},
  json={ "username": "sinopia-user", "password": "a-secret-password"}
)

# Retrieve the JWT from the result's x-okapi-token header
jwt = result.headers.get("x-okapi-token")
```

**Comment by jgreben** [comment]
You can use the ones here: https://github.com/sul-dlss/shared_configs/blob/bd56f5822accf2b197d65970ae61dcd634bca9eb/config/settings/dev.yml#L7-L8
