### ISSUE TITLE
Deploy ILS-Middleware using AWS ECS

### ISSUE THREAD

**Issue by jermnelson** [LD4P/ils-middleware#96]
Given the problems we've experienced with deploying our Airflow environment using Kubernetes on AWS, follow the approach we took with DLME and deploy our Airflow instance as an ECS VM  instead (see DLME's https://github.com/sul-dlss/dlme-airflow/blob/main/.circleci/config.yml)

**Comment by jermnelson** [comment]
@aaron-collier can TF PR https://github.com/sul-dlss/terraform-aws/pull/913 be moved out of draft so we can close this ticket? I was able to get the Dev ECS Airflow Stanford DAG working last night.

**Comment by aaron-collier** [comment]
@jermnelson oops - I neglected to change the title, but it's been ready... should be merged and close this.

**Comment by aaron-collier** [comment]
Merged this morning.
